name: Update README Badges

on:
  workflow_run:
    workflows: 
      - "ZK Theory Mathematical Platform CI/CD"
      - "Security & Dependency Audit"
    types:
      - completed

jobs:
  update-badges:
    name: Update Status Badges
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate badge data
        run: |
          echo "Generating badge data..."
          
          # CI Status Badge
          if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
            echo "CI_STATUS=passing" >> $GITHUB_ENV
            echo "CI_COLOR=brightgreen" >> $GITHUB_ENV
          else
            echo "CI_STATUS=failing" >> $GITHUB_ENV
            echo "CI_COLOR=red" >> $GITHUB_ENV
          fi
          
          # Extract performance data if available
          echo "PERFORMANCE_STATUS=monitored" >> $GITHUB_ENV
          echo "PERFORMANCE_COLOR=blue" >> $GITHUB_ENV
          
      - name: Update README with badges
        run: |
          echo "Updating README badges..."
          
          # Create badges section if it doesn't exist
          cat > .github/BADGES.md << EOF
          <!-- CI/CD Status Badges -->
          [![CI/CD Pipeline](https://img.shields.io/badge/CI%2FCD-${CI_STATUS}-${CI_COLOR})](https://github.com/${{ github.repository }}/actions/workflows/ci.yml)
          [![Security Scan](https://img.shields.io/badge/Security-monitored-blue)](https://github.com/${{ github.repository }}/actions/workflows/security.yml)
          [![Performance](https://img.shields.io/badge/Performance-${PERFORMANCE_STATUS}-${PERFORMANCE_COLOR})](https://github.com/${{ github.repository }}/actions/workflows/ci.yml)
          [![Mathematical Testing](https://img.shields.io/badge/Mathematical%20Testing-enabled-green)](https://github.com/${{ github.repository }}/blob/main/.github/workflows/README.md)
          
          <!-- Test Coverage and Quality -->
          [![Test Coverage](https://img.shields.io/badge/Coverage-80%25+-brightgreen)](#test-coverage)
          [![Code Quality](https://img.shields.io/badge/Code%20Quality-TypeScript-blue)](https://www.typescriptlang.org/)
          [![Mathematical Libraries](https://img.shields.io/badge/Math%20Libraries-validated-green)](#mathematical-libraries)
          
          <!-- Browser Support -->
          [![Chromium](https://img.shields.io/badge/Chromium-supported-green)](https://playwright.dev/)
          [![Firefox](https://img.shields.io/badge/Firefox-supported-green)](https://playwright.dev/)
          [![WebKit](https://img.shields.io/badge/WebKit-supported-green)](https://playwright.dev/)
          
          <!-- Node.js Support -->
          [![Node.js 18](https://img.shields.io/badge/Node.js-18.x-green)](https://nodejs.org/)
          [![Node.js 20](https://img.shields.io/badge/Node.js-20.x-green)](https://nodejs.org/)
          EOF
          
      - name: Commit badge updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if [ -n "$(git status --porcelain)" ]; then
            git add .github/BADGES.md
            git commit -m "docs: Update CI/CD status badges [skip ci]"
            git push
          else
            echo "No badge changes to commit"
          fi